const Images = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};

const Stats = {
    LOAD: 'IMAGE_STATS_LOAD',
    LOAD_SUCCESS: 'IMAGE_STATS_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGE_STATS_LOAD_FAIL',
};

export { Images, Stats };
